spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mvc:
    view:
      prefix: templates
      suffix: .html
    static-path-pattern: /static/**

# TODO custom error 설정
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration

# TODO context path 추가 및 thymeleaf에 @{} 설명
#server:
#  servlet:
#    context-path: /admin

# TODO springboot 로깅 방법 설명 1. yaml, 2. logback.xml
logging:
  level:
    root: info
#    org:
#      springframework:
#        security: debug
